name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # GitHub Pages にデプロイするブランチを指定 (例: main ブランチ)

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' # Node.js のバージョンを指定 (必要に応じて変更)

      - name: Install dependencies
        run: npm install # npm を使用している場合

      - name: Build project # プロジェクトのビルド手順 (必要に応じて変更)
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist # ビルド成果物が出力されるディレクトリ (必要に応じて変更)